server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        enabled: true
        register: true
        service-name: config-service
        health-check-interval: 10s
        health-check-timeout: 20s
        heartbeat:
          enabled: true
        ip-address: 106.15.233.99
        port: ${server.port}
        lifecycle:
          enabled: true
        scheme: http
        prefer-agent-address: false
        register-health-check: true
        tags: master
        query-passing: true
      retry:
        initial-interval: 1000
        max-attempts: 4
        max-interval: 1000
      host: 106.15.233.99
      port: 8500

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cloud-source/config-repo.git
          searchPaths: ${APP_LOCATE:dev}
#          username: user
#          password: pwd
---
spring:
  rabbitmq:
    host: 106.15.233.99
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'